### ISSUE TITLE
关于ngx_openresty-windows版本的一些建议

### ISSUE THREAD

**Issue by upupw** [openresty/openresty#101]
首先非常感谢开发者的努力，ngx_openresty最大的亮点就是在windows上实现了多进程工作，并发量不错。

以下为针对windows版本的建议：

1、希望以服务的方式运行。
作为一款webserver以服务的方式运行应该是必备的条件，一台服务器不可能一直保持单用户登录状态。也不可能每次重启服务器后再重新开启ngx_openresty。

2、希望指定用户运行。
指定用户运行可以增强安全性，因为ngx_openresty很多组件都有执行权限，不再是单纯的nginx内核了，再加上win上编译的nginx.exe开启了必须获得administrator权限才能运行，所以某个应用被黑后即可获得管理员权限，后果很严重。

3、希望组件动态加载可以在配置文件中单独开启或关闭
组件动态加载有利于减少运行负担，后续增加新组件也不需要重新全部编译，只需修改配置文件，方便运维。

**Comment by agentzh** [comment]
@upupw Thank you for your suggestions. But please no Chinese here. You're recommended to post Chinese to the openresty (Chinese) mailing list instead. Please see http://openresty.org/#Community for more details. Thank you for your cooperation!

Regarding your questions, I'm not aware of any (official) Windows version of OpenResty. What kind of Windows version are you talking about here? Are you referring to this "Windows nginx" thing?

http://nginx-win.ecsds.eu/

If yes, then it is something contributed by a guy in the community. It's not an official Windows version of OpenResty at all :)

**Comment by guanhui07** [comment]
oh

**Comment by agentzh** [comment]
Well, there may be an official Windows port of ngx_openresty in the near future. But I cannot promise anything at this point :)

**Comment by agentzh** [comment]
Okay, ngx_openresty's build system can now directly build on Windows using the MinGW/MSYS toolchain. See the docs here:

https://github.com/openresty/ngx_openresty/blob/master/doc/README-win32.md

@upupw Regarding your feature requests, they are more about the NGINX core rather than the OpenResty bundle itself. Anyway, you're welcome to try my binary build below:

https://openresty.org/download/ngx_openresty-1.9.3.2rc1.3-win32.zip

**Comment by antonheryanto** [comment]
wow that very good, will benefit lot of other developer who using windows. I have tested at my window 2008 server and running perfectly. would the windows binary available officially when openresty 1.9.3.2 release ?

**Comment by agentzh** [comment]
@antonheryanto Yes, of course. Thanks for your feedback!
