### ISSUE TITLE
Unable to change log format

### ISSUE THREAD

**Issue by kracekumar** [openresty/openresty#157]
My API server runs on AWS, behind load balancer ELB. Openresty nginx logs prints `ELB` IP rather  than client address. Changing the log format didn't help.

```
real_ip_header X-Forwarded-For;
set_real_ip_from 0.0.0.0/0;

log_format main '$remote_addr - $remote_user $time_local '
               '"$request" $status $body_bytes_sent "$http_referer" '
                '"$http_user_agent" "$http_x_forwarded_for"' ;
access_log /var/log/nginx/access.log;
```

Tried various combinations like `proxy_protocol` and all other answer in nginx and stackoverflow site.

Then came across, `log_by_lua` and added snippet under `location`

```
log_by_lua '
                           
                           local log_dict = ngx.shared.log_dict
                           ngx.say(ngx.var.remote_addr)
                           ngx.say("bye")
                           # ngx.say(log_dict)
                ';
```

The log statements aren't printed in access log section. 

Can I know the right way to log `remote_addr` along with other data.

**Comment by agentzh** [comment]
@kracekumar `ngx.say` always generates response body data which means that using it in the context of `log_by_lua*` always *fails* (if you check its return values) because at the log phase the response is already sent out in full.

For your purpose, you define a log format called `main` via the `log_format` directive but you never reference it in the `access_log` directive. The correct usage is

```nginx
access_log /var/log/nginx/access.log main;
```

See we reference the format as the second argument to the `access_log` directive. See the official documentation for the `log_format` and `access_log` directives for more details:

http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format

http://nginx.org/en/docs/http/ngx_http_log_module.html#access_log

So this is really a question of using the standard NGINX, not special to OpenResty at all.

**Comment by kracekumar** [comment]
Thanks @agentzh, that was my bad.
