### ISSUE TITLE
ngx_proxy, balancer_by_lua and tcp keepalives

### ISSUE THREAD

**Issue by alubbe** [openresty/openresty#176]
Assuming that the domains in `urls` resolve to the ones in `ips`, what are the differences between these two configurations? Does the first one use any tcp keepalives? Does the second one use 100 keepalives per IP (totalling a maximum 300 keepalives) or 100 in total (giving about 30-40 for each IP, assuming a uniform distribution of requests)? Anything else that's different?

```nginx
location / {
    set $proxy_pass_loc '';
    content_by_lua_block {
        local urls = ['http://example.com', 'http://api.example.com', 'http://www.example.com']
        ngx.var.proxy_pass_loc = urls[math.random(3)]  .. ngx.var.request_uri
        ngx.exec "/foo"
    }
}
location /foo {
    internal;
    proxy_pass $proxy_pass_loc;
}
```

```nginx
upstream foo {
    server 0.0.0.1;
    balancer_by_lua_block {
        local ips = ['93.184.216.34', '93.184.216.35', '93.184.216.36']
        require "balancer".set_current_peer(ips[math.random(3)], 80)
     }
    keepalive 100;
}

server {
    location / {
        proxy_pass http://foo;
     }
 }
```

**Comment by agentzh** [comment]
@alubbe Beware the special term "TCP keepalive". It means something very specific on the TCP protocol level:

http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html

I'm pretty sure here you mean "HTTP keepalive" instead.

Regarding your question, your first example does not involve any connection pool for your backend HTTP connections since there is no corresponding upstream {} configuration blocks and thus no "keepalive" configurations.

In the 2nd example, all your IPs share the same connection pool with the size limit of 100. But only connections with *matching addresses" can get reused. This means that if your ask for a peer for 92.184.216.34, then the in-pool connections with the address 93.184.216.35 can never get picked up for it.

**Comment by agentzh** [comment]
@alubbe BTW, such general discussions are recommended to move to the openresty-en mailing list instead. Please see

http://openresty.org/en/community.html

I'd rather keep the GitHub issues board for bug reports and patch review only.

**Comment by alubbe** [comment]
Thanks for the clarification around tcp and http keepalives - I was indeed looking for the latter. I will move the rest of the discussion to the mailing list.
