### ISSUE TITLE
backend 502 - 0.000 0.000 error

### ISSUE THREAD

**Issue by lenxeon** [openresty/openresty#216]
upstream backend {
                server ip1:8080;
                server ip2:8080;
                ip_hash;
        }

some error as the follow picture show

![image](https://cloud.githubusercontent.com/assets/251825/21305215/3afce584-c605-11e6-8b2b-4f9c825ed0a5.png)

full error log
[error_log_12_19.zip](https://github.com/openresty/openresty/files/660458/error_log_12_19.zip)

how to change config to fix it.

**Comment by agentzh** [comment]
@lenxeon There were nginx worker process crashes according to your error logs (though crashes do not lead to 502 errors, generally speaking). You should debug your crashes first anyway. See https://www.nginx.com/resources/admin-guide/debug/#backtrace

Ensure that you have not added any 3rd-party NGINX C modules or 3rd-party Lua C libraries that are not maintained by the OpenResty team since we do not support those exotic components.

**Comment by agentzh** [comment]
Consider it resolved.
