### ISSUE TITLE
Bit32 module not found

### ISSUE THREAD

**Issue by f1erro** [openresty/openresty#248]
Hello,

I am trying to integrate the 'luaposix' library with OpenResty.  It has a dependency on the "bit32" library.  If I try to `luarocks install bit32`, it tells me that this is a VM provided library, and thus does not install anything.

Is there any way to enable this library with an OpenResty which was installed with Homebrew?  I don't see any `configure` scripts or something similar with which to rebuild the LuaJit VM.

Please advise :)

Steps to reproduce:
`brew install openresty`
Follow instructions for installing `luarocks` from openresty docs
`luarocks install luaposix`
Run openresty with a lua file that has `local posix = require 'posix`

Running `nginx version: openresty/1.11.2.2`

**Comment by agentzh** [comment]
@f1erro It's all about Lua package search paths. See

https://github.com/openresty/lua-nginx-module#lua_package_path

and

https://github.com/openresty/lua-nginx-module#lua_package_cpath

**Comment by agentzh** [comment]
@f1erro You also need to ensure your Lua C libraries are using the Lua 5.1 ABI instead of using an incompatible 5.2/5.3 ABI. The latter won't even load into OpenResty.

Besides, be very careful when using LuaRocks libraries that are not aware of the OpenResty context, which may incur expensive system calls or even blocking I/O system calls, which will ruin your OpenResty server's performance.

**Comment by f1erro** [comment]
Thank you for the quick reply!  I love working with this OpenResty -- it's an awesome piece of software.  

I am not sure I understand the problem here.  I have been able to get OpenResty to find the `luaposix` module.  However, when I try to `require 'posix'`, I get an error message about the inability to find `bit32` module, which is VM provided.  So, does the Luajit 5.1 VM not provide this module?  I apologize if these are ignorant questions, this is new territory for me.

This is the library I am trying to install.  
https://github.com/luaposix/luaposix

It is not present in OPM, and the docs say using `luarocks` is discouraged.  What would you advise here?

Al regarding performance; my specific use case is to send a SIGHUP to nginx when instructed, so these posix calls would not be used very often.

Thanks!

**Comment by neomantra** [comment]
You might be able to get it to work if you rename `bit32` to `bit`.

Maybe you can do this with the LuaJIT FFI?  

```
local ffi = require 'ffi'
ffi.cdef('int kill(pid_t pid, int sig);')
local SIGHUP = 1  -- make sure this matches your platform
C.kill(ngx.var.pid, SIGHUP)
```

**Comment by f1erro** [comment]
Thanks neomantra!  I will try that and let you know :)

**Comment by agentzh** [comment]
@neomantra Well, I guess @f1erro wants to send HUP signal to the nginx master instead of the current worker process, otherwise it's not useful at all. But normal nginx worker processes are usually run under an unprivileged system account like `nobody`, so such workers do not have permissions to send any signals to the master which is usually run under a privileged system account like `root`.

We'll add such capabilities to OpenResty soon by introducing privileged "background worker processes" that is run under the same system account as the master but do not serve any requests directory from the wire. Such background workers will be able to send signals to the master.

**Comment by agentzh** [comment]
But yeah, using LuaJIT's FFI to call the `kill` C API directly can be more efficient than using external Lua libraries like `luaposix`.

**Comment by f1erro** [comment]
@agentzh you are right, I was hoping to send the HUP to the master, in order to initiate a restart.

**Comment by agentzh** [comment]
@f1erro BTW, `bit32` is a Lua 5.2 standard module. I think I've told you that Lua 5.2 is incompatible with the Lua 5.1 language that LuaJIT and OpenResty follows.

**Comment by agentzh** [comment]
@f1erro BTW, LuaJIT has its own standard bit standard library as an extension to the Lua 5.1 standard library:

http://luajit.org/extensions.html

That is the bit module that should be used in the OpenResty context.

**Comment by f1erro** [comment]
Thank you for your help
