### ISSUE TITLE
Why ngx.on_abort have no effect, The callback is registered successful, but it have no effect!

### ISSUE THREAD

**Issue by vos-land** [openresty/openresty#255]
server {
        listen       8005;
        server_name  aop_tencent;
        lua_check_client_abort on;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        limit_conn servers 40;
        limit_conn clients 1;
        limit_rate 800k;
     

        location ~* /downloads/ {
            rewrite_by_lua_block {
                local args = ngx.req.get_uri_args();
                local sessionId = "";
                local fileName = "";
                local range = "";
                for key, val in pairs(args) do
                    if key == "session_id" then
                      sessionId = val;
                    end
                end
                
                ngx.ctx.sessionId = sessionId;
                ngx.ctx.fileName = string.sub(ngx.var.uri, 12);
                print("sessionId = ", ngx.ctx.sessionId);
                print("fileName = ", ngx.ctx.fileName);

                local resHeaders = ngx.req.get_headers();        
                for key, val in pairs(resHeaders) do
                    if key == "range" then
                        local from, to, err = ngx.re.find(val, "-")
                        if (from) then
                            range = string.sub(val, from+1);
                        end
                    end
                end
                print("range = ", range);
                ngx.ctx.range = range;

                ngx.ctx.result = "";

                local function onAbort() 
                    ngx.ctx.result = "ABORTED";
                    print("session aborted: ", ngx.ctx.sessionId);
                end

                ngx.ctx.onAbort = onAbort;
                local ok, err = ngx.on_abort(ngx.ctx.onAbort)
                if not ok then
                    ngx.log(ngx.ERR, "failed to register the on_abort callback: ", err)
                else 
                    print("register on_abort callback successfully!", ok);
                end
            }

            log_by_lua_block {
                print("ctx-filename:", ngx.ctx.fileName);
                print("status:", ngx.status);
                local function fileSize(fileName) 
                    local files = ngx.shared.files;
                    local newName, n, err = ngx.re.sub(fileName, "\\.", "_");
                    local size, err = files:get(newName);
                    if not size then
                        print("failed to get file size of : ", fileName, " error:", err)
                        return -1
                    end

                    print("getFileSize: ", fileName, "  ", size)
                    return size 
                end

                local sessions = ngx.shared.sessions;
                local sessionId = ngx.ctx.sessionId;
                if (ngx.ctx.result == "" and (ngx.ctx.range == "" or ngx.ctx.range + 1 >= fileSize(ngx.ctx.fileName))) then
                    sessions:lpush("FINISHED", sessionId);
                    print("set session finished: sessionId=", sessionId, ", range=", ngx.ctx.range)
                elseif (ngx.ctx.result ~= "") then
                    --sessions:lpush(ngx.ctx.result, ngx.ctx.result);
                    --print("set session finished: sessionId=", sessionId, ", range=", ngx.ctx.range)
                end
            }
        }

**Comment by agentzh** [comment]
@vos-land The `ngx.on_abort()` feature has been carefully tested in this module's test suite:

https://github.com/openresty/lua-nginx-module/blob/master/t/101-on-abort.t#L34

And it has been used in production for years.

If you believe there is a bug here, please provide a *minimal* and *standalone* example that can easily reproduce the problem on others machines, in particular, on our side.

A minimal example means that you should keep removing things from your code/config while keeping the issue reproducible, until you cannot remove anything any more. Your example above is not minimal since it apparently contains many unrelated stuff.

A standalone example means that you have everything necessary to run the example on others' machines and others do not have to guess your mind to run and reproduce the problem on their side. Your example above is not standalone, since it lacks the content handler and we cannot run this on our side without guessing the most important missing bits.

Also, please do not paste your original configuration without analyses, especially when you paste a configuration that is not even runnable. It's not helpful at all. We are not gods and cannot guess your mind. Thanks for your cooperation.

**Comment by agentzh** [comment]
Consider it resolved.
