### ISSUE TITLE
2 Questions about NYI

### ISSUE THREAD

**Issue by qqee** [openresty/openresty#316]
Hi,
I have 2 questions I hope can be answered, thank you.

1,
`[TRACE --- (6/stitch) lib.lua:60 -- NYI: return to lower frame at init_by_lua:72]`
This NYI have any bad influence ?

2,
`[TRACE --- init_by_lua:46 -- NYI: bytecode 50 at init_by_lua:54]`
The FNEW, I rewrote this part of the code as a module and via [require], this error disappeared but a new error was generated
`[NYI: register coalescing too complex]`
I've controlled the local variable below 10, Is there any good solution to these two NYI ?

**Comment by agentzh** [comment]
@qqee Please join the openresty-en mailing list for such general usage questions instead of sending emails directly to me. Thanks for
your cooperation!

Please see https://openresty.org/en/community.html

BTW, your questions are more related to LuaJIT instead of OpenResty.

BTW 2: optimizing code in `init_by_lua*` makes little sense since it only runs once upon nginx startup or reloading.
