### ISSUE TITLE
Uri parameter overflow in OpenResty

### ISSUE THREAD

**Issue by Bypass007** [openresty/openresty#358]
###General Description
In OpenResty before 1.13.6.1, URI parameters were obtained using the ngx.req.get_uri_args and ngx.req.get_post_args functions that ignore parameters beyond the hundredth one,
which might allow remote attackers to bypass intended access restrictions or
interfere with certain Web Application Firewall (ngx_lua_waf or X-WAF) products.

###Details
First look at the official API document. There are two ways to get a URI: ngx.req.get_uri_args, ngx.req.get_post_args. The main difference between the two is the difference between the parameter sources, the ngx.req.get_uri_args acquires the URI request parameters, and the ngx.req.get_post_args gets the content from the post request.
Test case：
```
server {
   listen    80;
   server_name  localhost;
   location /print_param {
       content_by_lua_block {
           local arg = ngx.req.get_uri_args()
           for k,v in pairs(arg) do
               ngx.say("[GET ] key:", k, " v:", v)
           end
           ngx.req.read_body()
           local arg = ngx.req.get_post_args()
           for k,v in pairs(arg) do
               ngx.say("[POST] key:", k, " v:", v)
           end
       }
   }
}

```
**Uri parameter overflow**

What happens if we do not have a segment parameter, so I construct a test case that is convenient for display, a0-a9, 10*10, a total of 100 parameters, and then add the 101st parameters to the SQL injection Payload, let's see what happens?
Test cases:
```
 curl '127.0.0.1/test?
 a0=0&a0=0&a0=0&a0=0&a0=0&a0=0&a0=0&a0=0&a0=0&a0=0&
 a1=1&a1=1&a1=1&a1=1&a1=1&a1=1&a1=1&a1=1&a1=1&a1=1&
 a2=2&a2=2&a2=2&a2=2&a2=2&a2=2&a2=2&a2=2&a2=2&a2=2&
 a3=3&a3=3&a3=3&a3=3&a3=3&a3=3&a3=3&a3=3&a3=3&a3=3&
 a4=4&a4=4&a4=4&a4=4&a4=4&a4=4&a4=4&a4=4&a4=4&a4=4&
 a5=5&a5=5&a5=5&a5=5&a5=5&a5=5&a5=5&a5=5&a5=5&a5=5&
 a6=6&a6=6&a6=6&a6=6&a6=6&a6=6&a6=6&a6=6&a6=6&a6=6&
 a7=7&a7=7&a7=7&a7=7&a7=7&a7=7&a7=7&a7=7&a7=7&a7=7&
 a8=8&a8=8&a8=8&a8=8&a8=8&a8=8&a8=8&a8=8&a8=8&a8=8&
 a9=9&a9=9&a9=9&a9=9&a9=9&a9=9&a9=9&a9=9&a9=9&a9=9&
 id=1 union select 1,schema_name,3 from INFORMATION_SCHEMA.schemata'

```
Output results:
<img src="/Bypass007/vuln/raw/master/OpenResty/3.png" alt="" style="max-width:100%;">
It can be seen that using ngx.req.get_uri_args to get URI request parameters, we only get the first 100 parameters, and the 101st parameter is not obtained. 
Continue to construct a POST request and look at it.
<img src="/Bypass007/vuln/raw/master/OpenResty/4.png" alt="" style="max-width:100%;">
The content of post request obtained by ngx.req.get_post_args also obtains the first 100 parameters.

To sum up, the first 100 parameters can be obtained by ngx.req.get_uri_args and ngx.req.get_post_args. When the 101st parameters are submitted, the parameters of the URI parameters are overrun and the parameter values after 100th are not properly obtained. 

Based on the security protection of the ngx_lua development, it is impossible for the attacker to carry out effective security detection for the 100th subsequent parameters submitted by the attacker, thus bypassing the security defense.

###Impact products

**A、ngx_lua_waf**
Ngx_lua_waf is a web application firewall based on lua-nginx-module (openresty).
Using ngx.req.get_uri_args and ngx.req.get_post_args to get URI parameters.
github：https://github.com/loveshell/ngx_lua_waf
Interception effect diagram：
<img src="/Bypass007/vuln/raw/master/OpenResty/5.png" alt="" style="max-width:100%;">
Using uri parameter overflow Bypass：
<img src="/Bypass007/vuln/raw/master/OpenResty/6.png" alt="" style="max-width:100%;">

**B、X-WAF**
X-WAF is a cloud WAF system suitable for small and medium-sized businesses, enabling small and medium-sized businesses to have their own free cloud WAF conveniently.
Using ngx.req.get_uri_args and ngx.req.get_post_args to get URI parameters.
The official website：https://waf.xsec.io
github：https://github.com/xsec-lab/x-waf
Interception effect diagram：
<img src="/Bypass007/vuln/raw/master/OpenResty/7.png" alt="" style="max-width:100%;">
Using uri parameter overflow Bypass：
<img src="/Bypass007/vuln/raw/master/OpenResty/8.png" alt="" style="max-width:100%;">

**Comment by agentzh** [comment]
@Bypass007 The default 100 limit is for security reasons and is documented. You can increase that limit to fit your needs.

**Comment by Bypass007** [comment]
How should you set it up to avoid this problem? I didn't find this configuration parameter. I think it might be a debug.

**Comment by dndx** [comment]
@Bypass007 Please check the documentation for those two functions. They accept an optional parameter that tells it at most how many GET/POST parameters should be parsed.

**Comment by Bypass007** [comment]
I've seen this document, but if the default 100 limit is for security reasons, then more than one hundred of the parameters should be a refusal, not a state. And this has affected the open source WAF of the basic OpenRestry.

**Comment by Bypass007** [comment]
The default is 100 limits, and even if the optional parameter is 200 or 300, the OpenResty - based security can be easily bypassed if the attacker's parameter exceeds the limit, and there is still a URI parameter overflow problem. I think there is a great security risk.

I suggest that if we exceed the number of parameter restrictions, we should discard this HTTP package instead of directly issuing it.

**Comment by agentzh** [comment]
@Bypass007 Well, if you set the upper limit to 100, then if you indeed get 100 args, then you just reject. We cannot reject requests directly inside the OpenResty core, since it is better for the application to make the decision, which is much more flexible. Not every OpenResty application is a WAF anyway.

**Comment by Bypass007** [comment]
Not every OpenResty application is WAF, but OpenResty should be responsible for every user who uses it, including users who develop WAF based on OpenResty.

Here, we have to admit that using ngx.req.get_uri_args and ngx.req.get_post_args to get parameters is not safe, but most users don't know and don't think about it.

**Comment by Bypass007** [comment]
As an official, it is duty bound to remind users that when they use ngx.req.get_uri_args and ngx.req.get_post_args to get parameters, the default limit is 100, and more than one hundred will be released instead of rejecting HTTP packages.

I think the official should give a notice to remind users.

**Comment by spacewander** [comment]
@agentzh @Bypass007 
Maybe we could return `nil, "too many arguments"` when no args number is given and there is more arguments than the limitation? This change forces users to realize the overflow.

**Comment by dndx** [comment]
@spacewander This design breaks the current API behavior and does not solves the problem of user specifying a limit but still want to know if the limit has been reached. My propose would be to return a second argument `n` that specifies how many arguments has actually been parsed, like this:

```
args, n = ngx.req.get_uri_args(201)
if args and n > 200 then
    -- client attempted to exploit the function
end
```

Note that the `n` return value can also be used for other purposes, not just for determining argument overflows.

**Comment by spacewander** [comment]
> This design breaks the current API behavior 

It is why I said this change **forces** users to realize the overflow. Just break and force users to realize the problem and fix it. It is better than fixing it after being hacked.

Unless users read the documentation carefully, they will not check the second returned value, since there is only one returned value from `ngx.req.get_uri_args` for years. Not mention that the existence code.

**Comment by dndx** [comment]
The current behavior is clearly defined and user has certain expectation on how the behavior should stay consistent over time. Forcing user to read documentation by breaking existing code seems irresponsible and overall a bad idea. Not even to mention returning `nil` for the first argument may have other unexpected effects on existing code, you can't assume existing code does not check the return value and interpret it differently.

Also keep in mind that people using this API for various reasons, not just to write WAF. The current behavior may even be desirable in certain cases. The maintainer of the API should not be biased toward specific use case. As for WAF authors, they are expected to understand how those API works in order to write secure code, not the other way around.

**Comment by agentzh** [comment]
Now to help those open source WAF to detect truncation more efficiently (instead of counting the args or headers themselves), OpenResty's corresponding Lua API functions now return an extra string, `"truncated"`, to signal the case when there are too many URI args or POST args or request/response headers seen in the current request. Please refer to the official documentation in the git repository for more details.
