### ISSUE TITLE
Unable to configure without encrypted-session-nginx-module

### ISSUE THREAD

**Issue by theroyalstudent** [openresty/openresty#360]
Hi there,

I'm looking to build OpenResty on a server running Ubuntu 16.04 LTS, with OpenSSL 1.1.0h.
From what I have seen at the issues section of openresty/encrypted-session-nginx-module (issue 12), it is not actually possible to compile with a version of OpenSSL > 1.1.0g.

I have been looking for a way to disable the compilation of this module, but all I could find is `--without-http_ssl_module` in `util/configure`, which disables both SSL and http_encrypted_session.

There seems to be no way to build with only SSL and without http_encrypted_session, is there any idea to get around doing this? Using `--without-http_ssl_module` in conjunction with `--with-http_ssl_module` led to an error, caused by the check in `util/configure#L502`.

Do let me know, thank you!

**Comment by spacewander** [comment]
@theroyalstudent 
Maybe `--without-http_encrypted_session_module` should disable the encrypted-session-nginx-module?

However, it doesn't fix your problem, because the lua-nginx-module in the latest OpenResty release doesn't support OpenSSL 1.1.0 too. The OpenSSL 1.1.0 compatibility is already fixed in the master branch, so you could use the master branch of OpenResty if you want to build it with OpenSSL 1.1.0.

**Comment by agentzh** [comment]
@theroyalstudent Please try the following openresty preview version which should have full compatibility with OpenSSL 1.1.0h:

https://openresty.org/download/openresty-1.13.6.2rc0.tar.gz
