### ISSUE TITLE
`undefined symbol: EVP_MD_CTX_create` and potential OpenSSL issues?

### ISSUE THREAD

**Issue by cdbattags** [openresty/openresty#372]
plz start here: https://github.com/zmartzone/lua-resty-openidc/issues/159 

---

Hi folks! So this was working locally with the Dockerfile:

```
FROM openresty/openresty:alpine-fat

RUN mkdir /var/log/nginx
RUN apk add --no-cache openssl-dev
RUN apk add --no-cache git
RUN apk add --no-cache gcc
RUN luarocks install lua-resty-openidc
RUN cp /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.pem

ENTRYPOINT ["/usr/local/openresty/nginx/sbin/nginx", "-g", "daemon off;"]
```

But now as I go to install this on my box I'm getting a brand new error:

```
2018/05/22 22:13:12 [error] 9403#9403: *1 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/resty/evp.lua:216: /usr/local/openresty/luajit/lib/libluajit-5.1.so.2: undefined symbol: EVP_MD_CTX_create
stack traceback:
coroutine 0:
        [C]: in function '__index'
        /usr/local/share/lua/5.1/resty/evp.lua:216: in function 'verify'
        /usr/local/share/lua/5.1/resty/jwt.lua:812: in function 'verify_jwt_obj'
        /usr/local/share/lua/5.1/resty/openidc.lua:819: in function 'openidc_load_jwt_and_verify_crypto'
        /usr/local/share/lua/5.1/resty/openidc.lua:1390: in function 'jwt_verify'
        /usr/local/share/lua/5.1/resty/openidc.lua:1427: in function 'bearer_jwt_verify'
        access_by_lua(http_overrides.conf:461):24: in function <access_by_lua(http_overrides.conf:461):1>, client: 127.0.0.1, server: <redacted>, request: "GET <redacted> HTTP/1.1", host: "<redacted>"
```

I installed openresty version openresty/1.13.6.2 using:

```
wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add - && \
sudo apt-get -y install software-properties-common && \
sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main" && \
sudo apt-get update && \
sudo apt-get -y install openresty
```

Any help?

Edit:

I think I'm nearly there and some quick research brought me to https://stackoverflow.com/questions/46768071/openssl-linking-undefined-reference-evp-md-ctx-new-and-fre and how my nginx might be using the wrong linker? I know the method has been replaced.

Thanks for your help!

**Comment by agentzh** [comment]
@cdbattags It's just that your 3rd-party Lua modules fail to support OpenSSL 1.1.0 in the first place. Please note that OpenSSL 1.1.0 has an incompatible API with 1.0.2. There's nothing we can do on our side since those Lua modules are not maintained by us anyway.

**Comment by agentzh** [comment]
@cdbattags Starting from openresty 1.13.6.2, all our official pre-built packages have switched from OpenSSL 1.0.2 over to the OpenSSL 1.1.0 series. If you have to use OpenSSL 1.0.2 due to those 3rd-party Lua modules lacking OpenSSL 1.1.0 support, you should compile OpenResty from source yourself.

**Comment by cdbattags** [comment]
Hi @agentzh, thanks so much for all your support so far! It's been great diving into such an awesome project this past week or so.

As you can see with `v0.1.12` we now have support for OpenSSL 1.1.x series: https://github.com/cdbattags/lua-resty-jwt/tree/v0.1.12

Only issue left now is that I don't think my module for whatever reason is able to find the proper OpenSSL version that's bundled with OpenResty.

Here's my Dockerfile:

```
FROM ubuntu:14.04

RUN apt update

RUN apt -y install wget software-properties-common make gcc

RUN wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
RUN add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
RUN apt-get update
RUN apt -y install openresty

RUN mkdir /var/log/nginx
RUN opm install cdbattags/lua-resty-openidc
RUN cp /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.pem

ENTRYPOINT ["/usr/local/openresty/nginx/sbin/nginx", "-g", "daemon off;"]
```

Mind taking that for a quick spin and seeing where I'm going wrong?

**Comment by agentzh** [comment]
@cdbattags If you think it is an OpenResty issue, please provide a minimal and standalone example without using any 3rd-party libraries. We are not interested in nor have the time to help debugging those 3rd-party Lua modules which we know nothing about. Otherwise you should really contact the maintainers of those 3rd-party Lua modules as I've already suggested earlier.

**Comment by agentzh** [comment]
@cdbattags BTW, `EVP_MD_CTX_create` is indeed removed from OpenSSL 1.1.0 since 1.0.2. See:

```
$ /opt/ssl110/bin/openssl version
OpenSSL 1.1.0h  27 Mar 2018

$ nm -D /opt/ssl110/lib/libcrypto.so.1.1|grep EVP_MD_CTX_create

$ /opt/ssl102/bin/openssl version
OpenSSL 1.0.2n  7 Dec 2017

$ nm -D /opt/ssl102/lib/libcrypto.so.1.0.0|grep EVP_MD_CTX_create
0000000000115153 T EVP_MD_CTX_create
```

**Comment by cdbattags** [comment]
I appreciate the reply and I totally understand you "don't have the time" but I'm doing my duty to this open source community getting an abandoned package back up and running.

3rd party libraries are exactly what y'all want per the line `We already have 390 successful uploads across 158 distinct package names from 67 contributors. Come on, OPM authors!` from https://opm.openresty.org/, no?

So, thank you, but please bear with me and please mind the sass.

**Comment by cdbattags** [comment]
So I think I've almost tracked it down. The problem is that the shared objects (`.so`) files need to be added to the `ldconfig` for FFI to work properly, no?

**Comment by cdbattags** [comment]
Aha! Ok, developer error! Looks like @cybrq-as and I didn't look through his PR as well as we should have!

**Comment by agentzh** [comment]
@cdbattags Everyone can upload packages to OPM. We cannot support every single OPM package that is not maintained by us. BTW, we already have ~100 open source projects to maintain ourselves.

OpenResty uses RPATH to look up .so files, not through ldconfig since that way we would mess up with the operating system's openssl with our own openssl libraries.

**Comment by cdbattags** [comment]
That’s just it, no? ~100 with a team of how many? How else am I supposed to get context and dive into development except by loud mouthing my way through the gate? In this case my question did specifically pertain to OpenResty in the end, no? Maybe first step will be documenting my experience for new devs like myself and opening a PR? Where might I add something such as this?

Thanks again for your support and can't wait to work again with ya soon! 👍🏻😉

**Comment by agentzh** [comment]
@cdbattags As I said before, it is better to contact the maintainers of the 3rd-party Lua libraries you ran problems into. This place is for real issues inside the OpenResty itself. This issue has nothing to do with OpenResty itself since there is no bugs or no actions required on our side. It's the 3rd-party Lua module you're using lacks proper support for OpenSSL 1.1.0, which I made it clear at the very beginning.

If you have no clues about something, better ask on the openresty-en mailing list instead for such general inquiries. Please see

http://openresty.org/en/community.html

The github issues board is reserved for serious development discussions and true bug reports or feature requests.

Thanks for your understanding.

BTW, I'm not blaming you for anything, just trying to make it clear about the recommended practices in this community. Oh, and welcome to the OpenResty community!
