### ISSUE TITLE
openresty-1.11.2.5 rpm package broken dependency

### ISSUE THREAD

**Issue by azmng** [openresty/openresty#385]
Hi Openresty community,

I have found an issue with openresty-1.11.2.5-2 rpm. It depends on openresty-openssl package which got updated recently. Last two releases of openresty-openssl (1.1.0h-1, 1.1.0h-3) lacks libssl.so.1.0.0 so you are getting following errors:

> Starting nginx: /usr/local/openresty/nginx/sbin/nginx: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

In order to solve the issue you have to manually downgrade the openresty-openssl package to version 1.0.2k-1

Expected result: openresty-1.11.2.5-2 rpm should work by default
Kindly advise.

**Comment by agentzh** [comment]
@azmng This is tricky because openssl 1.1.0 breaks backward compatibility with openssl 1.0.2. The rpm package of openresty uses ">=" condition for the openssl package since it wants to preserve the ability to update openssl only. Using "=" here is not desired given the pace of openssl security updates. I'm not sure if there is a way to address this nicely without changing the package name of the `openresty-openssl` package, which is not desired.

**Comment by agentzh** [comment]
@azmng The idea is that the user should upgrade everything by default. Then there will be no problem (the latest openresty package always works with the latest openresty-openssl package anyway). Given that you are already controlling what to upgrade and what not, I think it's better for you to also control what exact versions of a package you want to upgrade will get upgraded when other related packages are not upgraded.
