### ISSUE TITLE
Memory Leak in ngx.re.*

### ISSUE THREAD

**Issue by zvtr** [openresty/openresty#390]
OS: CentOS 7.0
Version: nginx version: openresty/1.13.6.2

1. install openresty step by step from(http://openresty.org/en/linux-packages.html)
2. configure nginx.conf's location block, add:  **access_by_lua "ngx.re.find('hello', 'world)', 'isjo')";**
3. run nginx with command **/usr/local/openresty/nginx/sbin/nginx**
4. **top | grep nginx** watch mem used by nginx increasing fastly when **ab -n 100000 -c 20 http://127.0.0.1/**

other info:
1. memory increasing fastly when pattern is **world)**
2. nginx running normal when pattern is **(world**
3. nginx running normal when pattern is **world**
4. openresty-valgrind's nginx running normal when pattern is **world)**

**Comment by agentzh** [comment]
@zvtr You know that `world)` is not even a valid regex, right? If you check the return values of `ngx.re.find` (which you should, really), you'll note the first 2 values are nil and the 3rd value is the following error string:

```
pcre_compile() failed: unmatched parentheses in "world)" at ")"
```

The leak happens because it allocates memory in the global nginx memory pool and there's no way to release small blocks before the pool itself is destroyed (which is upon worker exiting). You are not seeing leaks with `openresty-valgrind` because it disables nginx's memory pools so that small blocks can be freed immediately.

I agree we should not leak memory even on bad regexes like this. And indeed our new FFI-based implementation for `ngx.re.find` does not have this issue. You can try it out yourself by adding the following line to the `http {}` block of your `nginx.conf`:

```nginx
init_by_lua_block { require "resty.core" }
```

Plus, the FFI-based implementation is usually much faster.

We'll retire the current default CFunction-based implementation soon anyway. And the users should always explicitly use `resty.core` module bundled by the OpenResty itself for now.

**Comment by agentzh** [comment]
@zvtr BTW, you should always specify `-k` option when using ab to avoid exhausting your local machine's ephemeral ports (or even better, using other tools supporting HTTP 1.1 keep-alive like weighttp and wrk).

**Comment by zvtr** [comment]
@agentzh I use gdb to debug with it use config **access_by_lua "ngx.re.find('hello', 'world', 'o')";**
Output as follow:
```bash
# gdb /usr/local/openresty/nginx/sbin/nginx 
Reading symbols from /usr/local/openresty/nginx/sbin/nginx...done.
(gdb) b ngx_http_lua_regex.c:320
Breakpoint 1 at 0x4c84cb: file ../ngx_lua-0.10.11/src/ngx_http_lua_regex.c, line 320.
(gdb) r
Starting program: /usr/local/openresty/nginx/sbin/nginx 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Breakpoint 1, ngx_http_lua_ngx_re_match_helper (L=0x40010260, wantcaps=0) at ../ngx_lua-0.10.11/src/ngx_http_lua_regex.c:323
323         re_comp.pattern = pat;
(gdb) set print pretty on
(gdb) print *lmcf->pool
$1 = {
  d = {
    last = 0x7dbfd0 "", 
    end = 0x7dbfd0 "", 
    next = 0x7e1000, 
    failed = 4
  }, 
  max = 4095, 
  current = 0x7d7fd0, 
  chain = 0x0, 
  large = 0x7fed00, 
  cleanup = 0x7fefe8, 
  log = 0x7d8038
}
(gdb) print *r->pool 
$2 = {
  d = {
    last = 0x7e76a0 "", 
    end = 0x7e7820 "", 
    next = 0x7dbfe0, 
    failed = 0
  }, 
  max = 4016, 
  current = 0x7e6820, 
  chain = 0x0, 
  large = 0x0, 
  cleanup = 0x0, 
  log = 0x7d7390
}
```
It seems that we didn't check whether pool size is 0 before we use `ngx_http_lua_pcre_malloc_init` to replace pcre_malloc with ngx_http_lua_pcre_malloc which use a empty pool
As `lmcf->pool.d`'s `end - last` is zero.
So, I wonder Whether nginx will help us handling this condition in `ngx_palloc` ?

**Comment by agentzh** [comment]
@zvtr Did you read my comments above? Better not waste your time on this. I already suggested you the correct way to avoid this. Please read it.

**Comment by agentzh** [comment]
@zvtr Your gdb analysis makes no sense to me since you really have no ideas about how these things actually work (like how the ngx.re API works and how the nginx memory pools work). So better read all the relevant C code before making wild guesses simply based on random gdb data structure dumps. That would never be helpful, unfortunately, just like shooting in the darkness.
