### ISSUE TITLE
nginx return data without body part

### ISSUE THREAD

**Issue by warrenwx** [openresty/openresty#449]
version: ngx.1.4.1
A query request was sent to nginx, while I got response without body part. Then I found that the response data return back with ngx.print(data), the statement isn't executed, then I try to decrease data size to about 100K Bytes from 3 M Bytes, everything goes well. My key configurations :

```
http{
    xxx
    client_body_buffer_size 200M;
    client_max_body_size 200M;
    client_header_buffer_size 128k;
    large_client_header_buffers 4 128k;
    proxy_buffer_size 64k;
    proxy_buffers 8 64k;
    fastcgi_buffer_size 128k;
    fastcgi_buffers 4 128k;
    xxx
}
```

Do someone have some ideas?

**Comment by agentzh** [comment]
@warrenwx OK, you mentioned `ngx.print()`. I suggest you provide a minimal and standalone example that we can easily reproduce the problem on our side. You mentioned `ngx.print(data)`, but your nginx configuration snippet never mentioned it. We cannot help you at all since we do not have the complete information.

**Comment by agentzh** [comment]
BTW, it's strongly recommended to use OpenResty directly to avoid known issues in the standard nginx core or in your own setup.

**Comment by warrenwx** [comment]
thanks, agentzh.
I will take your advises into  consideration, trying to reproduce with minimal conditions.

**Comment by warrenwx** [comment]
close temporarily
