### ISSUE TITLE
is there a start, stop, reload script

### ISSUE THREAD

**Issue by nkhine** [openresty/openresty#50]
hi i am running openresty server, and wanted to know if there is a rc.d/nginx script to start/stop/reload the server as `/usr/local/openresty/nginx/sbin/nginx` just starts it.

thanks

**Comment by mkozjak** [comment]
Still no script?

**Comment by agentzh** [comment]
@nkhine All our official OpenResty pre-built packages for Linux do provide an init script or an equivalent:

https://openresty.org/en/linux-packages.html

The source can be found in the [openresty/openresty-packaging](https://github.com/openresty/openresty-packaging).

**Comment by nkhine** [comment]
thanks @agentzh i had sorted it back in 2014 ;)

**Comment by olariuromeo** [comment]
I installed openresty in ubuntu 16.04, but nginx can not stop or start or reload, and not have init script

**Comment by agentzh** [comment]
@olariuromeo What package did you install? Have you seen my comment above?

https://github.com/openresty/openresty/issues/50#issuecomment-312922944

**Comment by olariuromeo** [comment]
https://openresty.org/en/linux-packages.html
Ubuntu

You can add our APT repository to your Ubuntu system so as to easily install our packages and receive updates in the future (via the apt-get update command). To add the repository, just run the following commands (only need to run once for each system):

    # import our GPG key:
    wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -

    # for installing the add-apt-repository command
    # (you can remove this package and its dependencies later):
    sudo apt-get -y install software-properties-common

    # add the our official APT repository:
    sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"

    # to update the APT index:
    sudo apt-get update

Then you can install a package, say, openresty, like this:

    sudo apt-get install openresty
-----------------------------------------------------------------------------------

**Comment by olariuromeo** [comment]
i have add now simbolic link and now working
# ln -s /usr/local/openresty/nginx/sbin/nginx /usr/sbin/nginx

**Comment by olariuromeo** [comment]
my openresty version openresty/1.13.6.1

**Comment by agentzh** [comment]
@olariuromeo Have you read this document?

https://openresty.org/en/deb-packages.html

**Comment by olariuromeo** [comment]
i have reinstaled all and get this error on status

root@openresty-1:~# sudo service openresty status
● openresty.service - full-fledged web platform
   Loaded: loaded (/lib/systemd/system/openresty.service; enabled; vendor preset: enabled)
   Active: active (running) since Jo 2018-03-29 04:35:41 UTC; 6s ago
  Process: 3211 ExecStop=/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 --pidfile /usr/local/openresty/nginx/logs/nginx.pid (c
  Process: 3227 ExecStart=/usr/local/openresty/nginx/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 3216 ExecStartPre=/usr/local/openresty/nginx/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCC
 Main PID: 3231 (nginx)
    Tasks: 2
   Memory: 1.9M
      CPU: 14ms
   CGroup: /system.slice/openresty.service
           ├─3231 nginx: master process /usr/local/openresty/nginx/sbin/nginx -g daemon on; master_process on
           └─3232 nginx: worker process                                                 

mar 29 04:35:41 openresty-1 systemd[1]: Starting full-fledged web platform...
mar 29 04:35:41 openresty-1 systemd[1]: openresty.service: Failed to read PID from file /usr/local/openresty/nginx/logs/nginx.pid: In
mar 29 04:35:41 openresty-1 systemd[1]: Started full-fledged web platform.
lines 1-17/17 (END)

**Comment by olariuromeo** [comment]
So how to start/stop/reload nginx.conf after we start openresty? ned to restart webserver every time?. if they give reload to openresty, nginx  does not reload a new configuration. Does anyone know that?

**Comment by agentzh** [comment]
@olariuromeo Seems like you are not reading the deb-packages document mentioned above carefully enough. To quote:

> Other service actions supported are stop, restart, and reload.

So you just need `reload` here.

**Comment by kuchaguangjie** [comment]
@olariuromeo For ubuntu, try:

> sudo systemctl <start | stop | restart | reload> openresty
