### ISSUE TITLE
openresty1.15.8.1 about "local"

### ISSUE THREAD

**Issue by sunhuanyao** [openresty/openresty#510]
i just coding like this above,

local zl = require "zlib"

but it takes a warning :  [warn] 17481#0: *30394 [lua] _G write guard:12: writing a global lua variable ('zlib') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables.  
zlib is a file named zlib.so

**Comment by dndx** [comment]
This is caused by `lua-zlib`'s use of `luaL_register` (https://github.com/brimworks/lua-zlib/blob/master/lua_zlib.c#L1263).

According to the [docs](https://pgl.yoyo.org/luai/i/luaL_register), `luaL_register` "sets it as the value of the global variable libname", which in this case would be `_G.zlib`.

What you may do is preload the library by calling `require "zlib"` in `init` phase, instead of requiring it in the requests.

**Comment by thibaultcha** [comment]
Given @dndx's advice is entirely correct, I'll consider this answered and will close the topic. Best of luck @sunhuanyao.

**Comment by sunhuanyao** [comment]
Thanks a lot!

**Comment by shixiaoliu** [comment]
like this:
https://github.com/openresty/lua-nginx-module#init_by_lua
