### ISSUE TITLE
openresty lua读取request body为nil

### ISSUE THREAD

**Issue by Mengxiangwo** [openresty/openresty#520]
通过lua读取request body，会出现偶尔读取不到request body的情况，而且该情况会随着openresty运行时间而增加。

![image](https://user-images.githubusercontent.com/26129573/63750690-891b2d80-c8e0-11e9-84fb-022d50d01213.png)

![image](https://user-images.githubusercontent.com/26129573/63750668-7acd1180-c8e0-11e9-8c81-0e52ebdc5d1f.png)

通过进行线上添加日志的方式，发现出现data等于nil的情况，但是并没有生成log

**Comment by agentzh** [comment]
@Mengxiangwo Please, do not use Chinese here. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list instead. Please see https://openresty.org/en/community.html Thanks for your cooperation.

Regarding your question, you'll need to prepare a minimal and self-contained example so that we can reproduce the problem on our side in order to debug such issues. We never observed such things in our own setups or our commercial customers' setups nor receive any reports from the open source community. Otherwise we'll need to use OpenResty Trace to analyze your online setups alive.
