### ISSUE TITLE
ETA for upgrading to nginx 1.17.3 because http/2 related security issues

### ISSUE THREAD

**Issue by dev0pz** [openresty/openresty#527]
Do you have any potential ETA for the upgrading to nginx 1.17.3 because last well known http/2 related security issues? 

context:
Security: when using HTTP/2 a client might cause excessive memory consumption and CPU usage (CVE-2019-9511, CVE-2019-9513, CVE-2019-9516)

Thanks

**Comment by pgsimpso** [comment]
If OpenResty doesn't want to jump directly to nginx 1.17.3, this issue is also fixed in 1.16.1. Either way, would be good to see a fix for this soon.

https://www.tenable.com/plugins/nessus/127907

**Comment by travisbell** [comment]
Looks like OR (head) was upgraded to 1.17.1 [back in July](https://github.com/openresty/openresty/commit/cef09e553fbd85b14c94aec6a15635d474914da3) and then @thibaultcha [just updated](https://github.com/openresty/openresty/commit/bad7098d88675725a505a0db510dac797050461b) to 1.17.4 3 days ago. So the patches should be committed.

So I guess the question is more around what an estimated time frame looks like to see OR get the 1.17.x version bump. There's some other fixes for `ngx.re` that are fixed in 1.17.x as well, so I'm hoping it's soon-ish. 🤞

**Comment by thibaultcha** [comment]
OpenResty [1.15.8.2](https://github.com/openresty/openresty/releases/tag/v1.15.8.2) was already released on August 14th with the HTTP/2 patches mentioned here. We'll release 1.17.x.1 when it will be ready.
