### ISSUE TITLE
Ubuntu focal apt repo currently broken

### ISSUE THREAD

**Issue by Zenexer** [openresty/openresty#613]
http://openresty.org/package/ubuntu/dists/focal/InRelease is currently out-of-date, causing `apt-get update` to fail on focal with the following error message:

```
Get:10 http://openresty.org/package/ubuntu focal/main amd64 Packages [5,885 B]
Err:10 http://openresty.org/package/ubuntu focal/main amd64 Packages
File has unexpected size (6304 != 5885). Mirror sync in progress? [IP: 174.138.55.201 80]
Hashes of expected file:
   - Filesize:5885 [weak]
   - SHA256:56e3996d362541d964633b1b845671091873cdc37ff509b6600de04219570c1f
   - SHA1:4dc43b7edeca83f6c3828ae64a7b47e59da9d650 [weak]
   - MD5Sum:6aeae73eb85c265f5550fe136ab94f5d [weak]
  Release file created at: Fri, 17 Apr 2020 01:07:51 +0000
Fetched 2,817 B in 1s (3,369 B/s)
Reading package lists... Done
E: Failed to fetch http://openresty.org/package/ubuntu/dists/focal/main/binary-amd64/Packages.gz  File has unexpected size (6304 != 5885). Mirror sync in progress? [IP: 174.138.55.201 80]
   Hashes of expected file:
    - Filesize:5885 [weak]
    - SHA256:56e3996d362541d964633b1b845671091873cdc37ff509b6600de04219570c1f
    - SHA1:4dc43b7edeca83f6c3828ae64a7b47e59da9d650 [weak]
    - MD5Sum:6aeae73eb85c265f5550fe136ab94f5d [weak]
   Release file created at: Fri, 17 Apr 2020 01:07:51 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

http://openresty.org/package/ubuntu/dists/focal/Release shows a newer date with the correct size for Packages.gz.

**Comment by o7n** [comment]
@agentzh do you know what is going on?

**Comment by Webifi** [comment]
http://openresty.org/package/ubuntu/dists/focal/InRelease seems to be stale on openresty.org if requested without an "Accept-Encoding: gzip, deflate" header.

This gets the correct file:
curl -H "Accept-Encoding: gzip, deflate" http://openresty.org/package/ubuntu/dists/focal/InRelease --output InRelease

This does not:
curl -H http://openresty.org/package/ubuntu/dists/focal/InRelease --output InRelease

Unfortunately, apt-get update does not send "Accept-Encoding: gzip, deflate" in its requests, so we get a stale file.   Hopefully someone can get this fixed in a hurry -- I have a few new machines I'm trying to configure, but am blocked by this issue.

**Comment by o7n** [comment]
This issue seems to have been resolved.

**Comment by Zenexer** [comment]
Looks like it's fixed.
