### ISSUE TITLE
Blocked builds on Travis

### ISSUE THREAD

**Issue by Prabhav-Thali** [openresty/openresty#850]
It is observed that the builds for Openresty are blocked on [Travis ](https://travis-ci.com/github/openresty/openresty)due to negative credit balance.
As per the Travis [doc](https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source), Travis fully supports the OSS teams and allocates them more credits after they apply for the same.
Could you please open a request with Travis CI support stating that you'd like to be considered for the OSS allotment?
Please refer to the Travis [blog ](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)for more details on opening support requests with Travis.

**Comment by neomantra** [comment]
The Docker image tooling uses Travis as well.   I had requested *and* was granted generous amounts of minutes and I have plenty left.   I was pretty sure the Docker builds were consuming *my* OSS minutes, because once my minutes were granted, the builds flowed again.  

However, now I'm not so sure because the Docker builds are not proceeding because of this negative balance.   I will reach out to Travis on my behalf.

**Comment by neomantra** [comment]
I reached out to Travis-CI.com and described the situation.  My personal OSS build minutes were not being consumed. 

However, they granted OpenResty OSS build minutes and I see the Docker builds working again.  I presume the same will be the case with the other OpenResty repos. 

Big shout out and many thank yous to Travis-CI.com and their continuing support of Open Source Software. 🎉

**Comment by Prabhav-Thali** [comment]
@neomantra Thank you for the updates. We are happy to continue our support in every way possible :slightly_smiling_face: . Will close the issue once a build gets executed.

**Comment by Prabhav-Thali** [comment]
Hi @neomantra 
Observing the warning related to a negative credit balance again in Travis CI, could you please take a look?
