### ISSUE TITLE
lua incompatibility issue with latest Nginx version 1.24

### ISSUE THREAD

**Issue by AnitaThakur671** [openresty/openresty#922]
Hi team, 

We are trying to upgrade Nginx version from v1.22 to v.124 and facing compatibility issues with lua version.

After Nginx version upgrade to v1.24 it keeps crashing with errors like this:

|LOG_LINE| 26/Jul/2023:12:43:22 +0000 [edge.access.marriott_default:-:REQUEST ID=] { host: "10.221.70.200", remote_addr: "10.221.70.1", request: "GET /healthCheck HTTP/1.1", status: 200, referer: "-", request_time: 0.000, connection: "1342", connection_requests: "1", location: "", upstream_location_response: "-", bytes_sent: "247", client_ip: "-", x_dynaTrace: "-" }
2023/07/26 12:43:22 **[alert] 184#0: worker process 201 exited on signal 11 (core dumped)**
|LOG_LINE| 26/Jul/2023:12:43:32 +0000 [edge.access.marriott_default:-:REQUEST ID=] { host: "10.221.70.200", remote_addr: "10.221.70.1", request: "GET /healthCheck HTTP/1.1", status: 200, referer: "-", request_time: 0.000, connection: "1344", connection_requests: "1", location: "", upstream_location_response: "-", bytes_sent: "247", client_ip: "-", x_dynaTrace: "-" }

2023/07/26 12:43:25 **[alert] 184#0: worker process 198 exited on signal 9**

Suspecting this to be a lua issue, we have tried different versions of lua, but to no avail.
Following table shows key combinations we have tried:
**nginx              lua-nginx-module   resty core                    status**
1.24.0             0.10.22             v.0.1.24                     not working 
1.24.0             0.10.23             v0.1.25                      not working 
1.24.0             0.10.24             v0.1.25                      not working
1.24.0             0.10.24             v0.1.26                      not working

 We also tried to analyze the core files which are dumped into the working directory of Nginx and we are getting the 
below errors -

**Core was generated by `nginx: worker process'.**
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ngx_http_variable_headers_internal (r=0x1f414a0, v=0x1f42990, data=<optimized out>, sep=sep@entry=44 ',') at src/http/ngx_http_variables.c:840
840     src/http/ngx_http_variables.c: No such file or directory.
Ensure you have provided the following details while reporting a problem:

Due to this issue we are blocked from upgrading Nginx version. 

requesting help to resolve this issue.
Thanks.

**Comment by zhuizhuhaomeng** [comment]
OpenResty will support nginx 1.25+ in the next release.

**Comment by yashbhardwaj26** [comment]
Hi Team , 

I tried the nginx version 1.25.1 but still facing the same issue as mentioned by @AnitaThakur671. 

Issue description - 

 { host: "10.221.70.200", remote_addr: "10.221.70.1", request: "GET /healthCheck HTTP/1.1", status: 200, referer: "-", request_time: 0.000, connection: "1342", connection_requests: "1", location: "", upstream_location_response: "-", bytes_sent: "247", client_ip: "-", x_dynaTrace: "-" }
 **worker process 201 exited on signal 11 (core dumped)**
edge.access.marriott_default:-:REQUEST ID=] { host: "10.221.70.200", remote_addr: "10.221.70.1", request: "GET /healthCheck HTTP/1.1", status: 200, referer: "-", request_time: 0.000, connection: "1344", connection_requests: "1", location: "", upstream_location_response: "-", bytes_sent: "247", client_ip: "-", x_dynaTrace: "-" }

Due to this issue we are blocked from upgrading Nginx version.

requesting help to resolve this issue.
Thanks.

**Comment by zhuizhuhaomeng** [comment]
@yashbhardwaj26  would you please add a test case that can reproduce this issue to lua-nginx-module?

https://github.com/openresty/lua-nginx-module/tree/master/t

**Comment by shay-berman** [comment]
any updates?

**Comment by swananan** [comment]
Hi @shay-berman @yashbhardwaj26 this may be the same issue with https://github.com/openresty/lua-nginx-module/issues/2218#issuecomment-1707503748
Using the newest master branch of lua-nginx-module could help to resolve this issue.
